### ISSUE TITLE
Just minor stuff

### ISSUE THREAD

**Issue by exoosh** [ElliotKillick/windows-vs-linux-loader-architecture#1]
Hey there, thanks for the great writeup! Found some minor things and wanted to draw your attention to those.

> Since `_dl_load_lock` prot**e**cts the entire library

(missing e)

`GNU_STB_UNIQUE` -> `STB_GNU_UNIQUE`

(name is wrong)

**Comment by ElliotKillick** [comment]
Looks like I already caught the first typo in a document-wide grammar review. Thanks for catching the inconsistency with `STB_GNU_UNIQUE`: https://github.com/ElliotKillick/windows-vs-linux-loader-architecture/commit/65c04644bb89d959c552126b18b5aa513259ab32
